name: Build docker image and push
on:
  push:
    branches: 
    - master
jobs:
  build:
    runs-on: [ubuntu-18.04]
    name: build image
    steps:
      - uses: actions/checkout@v2.0.0
      - name: Docbker build
        run: docker build . -t docker.pkg.github.com/${{ github.repository }}/server:${{ github.sha }}
      - name: Docker login
        run: docker login docker.pkg.github.com -u valdemarceccon -p ${{ secrets.GITHUB_TOKEN }}
      - name: Docker push
        run: docker push docker.pkg.github.com/${{ github.repository }}/server:${{ github.sha }}

