name: Build docker image and push
on:
  push:
    branches: 
    - master
jobs:
  build:
    runs-on: [ubuntu-18.04]
    name: build image
    steps:
      - uses: actions/checkout@v2.0.0
      - name: Docbker build
        run: docker build . -t docker.pkg.github.com/valdemarceccon/fiddling-with-github-actions/app:1.0 
